### ISSUE TITLE
Updating the requirements

### ISSUE THREAD

**Issue by menesro** [michael-emmi/violat#5]
The list of requirements should be updated when using Java Pathfinder:
- Java Pathfinder imposes a version of Java 8, e.g., 1.8.0_231
- Java Pathfinder itself (https://github.com/javapathfinder/jpf-core)
- Older versions of Gradle seem to create troubles when having multiple installations of Java. Everything works fine with Gradle 6.0.1

**Comment by michael-emmi** [comment]
v1.0.13 fixes this for JPF, and even complains properly when it can’t find JPF.

Is it true that JPF imposes Java 8?

Also: not sure how to constrain Gradle… any idea what the minimum version is?

**Comment by michael-emmi** [comment]
Maybe this implies Java 8 is required?
https://github.com/javapathfinder/jpf-core/issues/183#issuecomment-477988228
