### ISSUE TITLE
Bug - Java Pathfinder and ConcurrentSkipListMap

### ISSUE THREAD

**Issue by menesro** [michael-emmi/violat#8]
The following command produces an error related to reading the output of Java Pathfinder:

violat-validator ../test_violat/ConcurrentSkipListMap2.json --tester "Java Pathfinder" --schema "{ put(0, 0); isEmpty(); ceilingKey(0)} || {values(); remove(1)}"

The .json file includes a specification where the visibility of all methods is complete: 

{
  "class": "java.util.concurrent.ConcurrentSkipListMap",
  "harnessParameters": {
        "invocations": 4
  },
  "methods": [
    {
      "name": "containsKey",
      "parameters": [{"type": "java.lang.Object"}],
      "void": false,
      "readonly": true,
      "trusted": true,
      "visibility": "complete"
    },
    {
      "name": "get",
      "parameters": [{"type": "java.lang.Object"}],
      "void": false,
      "readonly": true,
      "trusted": true,
      "visibility": "complete"
    },
    {
      "name": "put",
      "parameters": [{"type": "java.lang.Object"}, {"type": "java.lang.Object"}],
      "void": false,
      "readonly": false,
      "trusted": true,
      "visibility": "complete"
    },
    {
      "name": "remove",
      "parameters": [{"type": "java.lang.Object"}],
      "void": false,
      "readonly": false,
      "trusted": true,
      "visibility": "complete"
    },
    {
      "name": "containsValue",
      "parameters": [{"type": "java.lang.Object"}],
      "void": false,
      "readonly": true,
      "trusted": false,
      "visibility": "complete"
    },
    {
      "name": "entrySet",
      "parameters": [],
      "void": false,
      "readonly": true,
      "trusted": false,
      "visibility": "complete"
    },
    {
      "name": "keySet",
      "parameters": [],
      "void": false,
      "readonly": true,
      "visibility": "complete"
    },
    {
      "name": "size",
      "parameters": [],
      "void": false,
      "readonly": true,
      "trusted": false,
      "visibility": "complete"
    },
    {
      "name": "toString",
      "parameters": [],
      "void": false,
      "readonly": true,
      "trusted": false,
      "visibility": "complete"
    },
    {
      "name": "values",
      "parameters": [],
      "void": false,
      "readonly": true,
      "trusted": false,
      "visibility": "complete"
    },
    {
      "name": "ceilingKey",
      "parameters": [{"type": "java.lang.Object"}],
      "void": false,
      "readonly": true,
      "visibility": "complete"
    },
    {
      "name": "firstKey",
      "parameters": [],
      "void": false,
      "readonly": true,
      "visibility": "complete"
    },
    {
      "name": "lastKey",
      "parameters": [],
      "void": false,
      "readonly": true,
      "visibility": "complete"
    },
    {
      "name": "floorKey",
      "parameters": [{"type": "java.lang.Object"}],
      "void": false,
      "readonly": true,
      "visibility": "complete"
    },
    {
      "name": "higherKey",
      "parameters": [{"type": "java.lang.Object"}],
      "void": false,
      "readonly": true,
      "visibility": "complete"
    },
    {
      "name": "lowerKey",
      "parameters": [{"type": "java.lang.Object"}],
      "void": false,
      "readonly": true,
      "visibility": "complete"
    },
    {
      "name": "pollFirstEntry",
      "parameters": [],
      "void": false,
      "readonly": false,
      "trusted": false
    },
    {
      "name": "pollLastEntry",
      "parameters": [],
      "void": false,
      "readonly": false,
      "trusted": false
    },
    {
      "name": "isEmpty",
      "parameters": [],
      "void": false,
      "readonly": true,
      "visibility": "complete"
    },
    {
      "name": "headMap",
      "parameters": [{"type": "java.lang.Object"}],
      "void": false,
      "readonly": true,
      "trusted": false,
      "visibility": "complete"
    },
    {
      "name": "tailMap",
      "parameters": [{"type": "java.lang.Object"}],
      "void": false,
      "readonly": true,
      "trusted": false,
      "harnessParameters": {
        "invocations": 5
      },
      "visibility": "complete"
    },
    {
      "name": "putAll",
      "parameters": [{"type": {"java.lang.Object": "java.lang.Object"}}],
      "void": true,
      "readonly": false,
      "trusted": false,
      "harnessParameters": {
        "invocations": 3
      }
    },
    {
      "name": "clear",
      "parameters": [],
      "void": true,
      "readonly": false,
      "trusted": false
    }
  ]
}

**Comment by michael-emmi** [comment]
Something odd is happening with the ConcurrentSkipListMap in JPF:
```console
% cat Test.jpf && echo -- && cat Test.java && echo -- && javac Test.java && jpf Test.jpf          
target = Test
classpath = .
sourcepath = .
report.console.property_violation =
report.console.start =
report.console.finished =
search.multiple_errors = true

--
import java.util.concurrent.*;

public class Test {
    public static void main(String[] args) {
        System.out.println("Before");
        new ConcurrentSkipListMap<Integer,Integer>().put(1,1);
        System.out.println("After");
    }
}
--
Before
```
Using ConcurrentHashMap instead, the `After` is printed as expected:
```console
% cat Test.jpf && echo -- && cat Test.java && echo -- && javac Test.java && jpf Test.jpf
target = Test
classpath = .
sourcepath = .
report.console.property_violation =
report.console.start =
report.console.finished =
search.multiple_errors = true

--
import java.util.concurrent.*;

public class Test {
    public static void main(String[] args) {
        System.out.println("Before");
        new ConcurrentHashMap<Integer,Integer>().put(1,1);
        System.out.println("After");
    }
}
--
Before
After
```

**Comment by michael-emmi** [comment]
Opened an issue at javapathfinder/jpf-core#214
